project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: project.qmd
        text: Project 
      - href: labs.qmd
        text: Labs 
      - href: presentation.qmd
        text: Presentation
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

